#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEFAULT_TOKENIZER_PATH="${HOME}/.cache/huggingface/hub/models--Qwen--Qwen3-32B/snapshots/9216db5781bf21249d130ec9da846c4624c16137"

export RELEASE_LANE_ID="${RELEASE_LANE_ID:-rc_q}"
export RELEASE_CONTROLS_STRICT="${RELEASE_CONTROLS_STRICT:-true}"
export API_VERSION_LABEL="${API_VERSION_LABEL:-2026-03-30-rc-q}"
export API_AUTH_ENABLED="${API_AUTH_ENABLED:-true}"
export AUDIT_LOG_ENABLED="${AUDIT_LOG_ENABLED:-true}"
export ALLOW_ANONYMOUS_INTERNAL_SMOKE="${ALLOW_ANONYMOUS_INTERNAL_SMOKE:-false}"
export SESSION_STORE_BACKEND="${SESSION_STORE_BACKEND:-redis}"
export SESSION_STORE_REDIS_REQUIRED="${SESSION_STORE_REDIS_REQUIRED:-true}"
export SESSION_STORE_REDIS_PING_ON_STARTUP="${SESSION_STORE_REDIS_PING_ON_STARTUP:-true}"
export REDIS_URL="${REDIS_URL:-redis://127.0.0.1:6379/0}"
export SESSION_STORE_NAMESPACE="${SESSION_STORE_NAMESPACE:-hukuk-ai-rc-q}"
export TOKEN_ACCOUNTING_APPROXIMATE_FALLBACK="${TOKEN_ACCOUNTING_APPROXIMATE_FALLBACK:-false}"
export TOKEN_ACCOUNTING_TOKENIZER_PATH="${TOKEN_ACCOUNTING_TOKENIZER_PATH:-${DEFAULT_TOKENIZER_PATH}}"
export PARITY_TRACE_ENABLED="${PARITY_TRACE_ENABLED:-true}"
export RELEASE_CONTROLS_BOUNDARY_PROXY_ENABLED="${RELEASE_CONTROLS_BOUNDARY_PROXY_ENABLED:-false}"
export RELEASE_CONTROLS_PERIMETER_SESSION_ISOLATION="${RELEASE_CONTROLS_PERIMETER_SESSION_ISOLATION:-false}"

export GATEWAY_PORT="${GATEWAY_PORT:-8217}"
export LOCAL_TUNNEL_PORT="${LOCAL_TUNNEL_PORT:-30217}"
export LOG_NAME="${LOG_NAME:-faz36_rc_q_gateway.log}"
export PID_NAME="${PID_NAME:-faz36_rc_q_gateway.pid}"
export TUNNEL_LOG_NAME="${TUNNEL_LOG_NAME:-faz36_rc_q_tunnel.log}"
export TUNNEL_PID_NAME="${TUNNEL_PID_NAME:-faz36_rc_q_tunnel.pid}"
export AUDIT_LOG_PATH="${AUDIT_LOG_PATH:-${REPO_ROOT}/runtime_logs/faz36_rc_q_audit.jsonl}"
export TRACE_LOG_DIR="${TRACE_LOG_DIR:-${REPO_ROOT}/runtime_logs/faz36_rc_q_traces}"

cd "${REPO_ROOT}"
bash scripts/finetune/launch_local_candidate_gateway_dgx1_merged.sh
