#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEFAULT_TOKENIZER_PATH="${HOME}/.cache/huggingface/hub/models--Qwen--Qwen3-32B/snapshots/9216db5781bf21249d130ec9da846c4624c16137"

RC_KIND="${RC_KIND:-rc_j}"
TOPOLOGY_LEVEL="${TOPOLOGY_LEVEL:-L0}"
RC_SLUG="$(printf '%s' "${RC_KIND}" | tr '[:upper:]' '[:lower:]')"
LEVEL_SLUG="$(printf '%s' "${TOPOLOGY_LEVEL}" | tr '[:upper:]' '[:lower:]')"

case "${TOPOLOGY_LEVEL}" in
  L0) GATEWAY_PORT_DEFAULT=8121; LOCAL_TUNNEL_PORT_DEFAULT=30031 ;;
  L1) GATEWAY_PORT_DEFAULT=8122; LOCAL_TUNNEL_PORT_DEFAULT=30032 ;;
  L2) GATEWAY_PORT_DEFAULT=8123; LOCAL_TUNNEL_PORT_DEFAULT=30033 ;;
  L3) GATEWAY_PORT_DEFAULT=8124; LOCAL_TUNNEL_PORT_DEFAULT=30034 ;;
  L4) GATEWAY_PORT_DEFAULT=8125; LOCAL_TUNNEL_PORT_DEFAULT=30035 ;;
  L5) GATEWAY_PORT_DEFAULT=8126; LOCAL_TUNNEL_PORT_DEFAULT=30036 ;;
  L6) GATEWAY_PORT_DEFAULT=8127; LOCAL_TUNNEL_PORT_DEFAULT=30037 ;;
  L7) GATEWAY_PORT_DEFAULT=8128; LOCAL_TUNNEL_PORT_DEFAULT=30038 ;;
  *)
    echo "[FAIL] Unknown TOPOLOGY_LEVEL=${TOPOLOGY_LEVEL}" >&2
    exit 1
    ;;
esac

export RELEASE_LANE_ID="${RELEASE_LANE_ID:-${RC_SLUG}_${LEVEL_SLUG}}"
export API_VERSION_LABEL="${API_VERSION_LABEL:-2026-03-24-${RC_SLUG}-${LEVEL_SLUG}}"
export GATEWAY_PORT="${GATEWAY_PORT:-${GATEWAY_PORT_DEFAULT}}"
export LOCAL_TUNNEL_PORT="${LOCAL_TUNNEL_PORT:-${LOCAL_TUNNEL_PORT_DEFAULT}}"
export LOG_NAME="${LOG_NAME:-${RC_SLUG}_${LEVEL_SLUG}_gateway.log}"
export PID_NAME="${PID_NAME:-${RC_SLUG}_${LEVEL_SLUG}_gateway.pid}"
export TUNNEL_LOG_NAME="${TUNNEL_LOG_NAME:-${RC_SLUG}_${LEVEL_SLUG}_tunnel.log}"
export TUNNEL_PID_NAME="${TUNNEL_PID_NAME:-${RC_SLUG}_${LEVEL_SLUG}_tunnel.pid}"
export AUDIT_LOG_PATH="${AUDIT_LOG_PATH:-${REPO_ROOT}/runtime_logs/${RC_SLUG}_${LEVEL_SLUG}_audit.jsonl}"
export TRACE_LOG_DIR="${TRACE_LOG_DIR:-${REPO_ROOT}/runtime_logs/${RC_SLUG}_${LEVEL_SLUG}_traces}"
export SESSION_STORE_NAMESPACE="${SESSION_STORE_NAMESPACE:-hukuk-ai-${RC_SLUG}-${LEVEL_SLUG}}"
export PARITY_TRACE_ENABLED="${PARITY_TRACE_ENABLED:-true}"
export PARITY_TOPOLOGY_LABEL="${PARITY_TOPOLOGY_LABEL:-${TOPOLOGY_LEVEL}}"
export PARITY_GENERATION_CACHE_POLICY="${PARITY_GENERATION_CACHE_POLICY:-off}"
export PARITY_REQUEST_ORDERING="${PARITY_REQUEST_ORDERING:-serial}"
export PARITY_WORKER_COUNT="${PARITY_WORKER_COUNT:-1}"
export PARITY_PINNED_WORKER_ID="${PARITY_PINNED_WORKER_ID:-worker-0}"
export PARITY_FAILOVER_ENABLED="${PARITY_FAILOVER_ENABLED:-false}"
export PARITY_PARALLELISM_ENABLED="${PARITY_PARALLELISM_ENABLED:-false}"
export DGX_SEED="${DGX_SEED:-20260324}"
export DGX_RETRY_COUNT="${DGX_RETRY_COUNT:-0}"
export DGX_REQUEST_TIMEOUT_SECONDS="${DGX_REQUEST_TIMEOUT_SECONDS:-180}"

export RELEASE_CONTROLS_STRICT=false
export API_AUTH_ENABLED=false
export AUDIT_LOG_ENABLED=false
export ALLOW_ANONYMOUS_INTERNAL_SMOKE=true
export SESSION_STORE_BACKEND=memory
export SESSION_STORE_REDIS_REQUIRED=false
export TOKEN_ACCOUNTING_APPROXIMATE_FALLBACK=true
export PARITY_FRESH_CLIENT_PER_REQUEST=false
export PARITY_HARD_RESET_AFTER_REQUEST=false
export PARITY_PROCESS_MODE=shared_process
export PARITY_SESSION_NAMESPACE_MODE=fresh_per_request

case "${TOPOLOGY_LEVEL}" in
  L0)
    export PARITY_FRESH_CLIENT_PER_REQUEST=true
    export PARITY_PROCESS_MODE=fresh_process
    ;;
  L1)
    export PARITY_FRESH_CLIENT_PER_REQUEST=true
    export PARITY_PROCESS_MODE=fresh_process
    ;;
  L2)
    export PARITY_HARD_RESET_AFTER_REQUEST=true
    ;;
  L3)
    ;;
  L4|L5|L6|L7)
    export RELEASE_CONTROLS_STRICT=true
    export API_AUTH_ENABLED=true
    export AUDIT_LOG_ENABLED=true
    export ALLOW_ANONYMOUS_INTERNAL_SMOKE=false
    export SESSION_STORE_BACKEND=redis
    export SESSION_STORE_REDIS_REQUIRED=true
    export SESSION_STORE_REDIS_PING_ON_STARTUP=true
    export REDIS_URL="${REDIS_URL:-redis://127.0.0.1:6379/0}"
    export TOKEN_ACCOUNTING_APPROXIMATE_FALLBACK=false
    export TOKEN_ACCOUNTING_TOKENIZER_PATH="${TOKEN_ACCOUNTING_TOKENIZER_PATH:-${DEFAULT_TOKENIZER_PATH}}"
    ;;
esac

case "${TOPOLOGY_LEVEL}" in
  L6)
    export PARITY_WORKER_COUNT="${PARITY_WORKER_COUNT:-2}"
    export PARITY_PARALLELISM_ENABLED="${PARITY_PARALLELISM_ENABLED:-true}"
    export PARITY_REQUEST_ORDERING="${PARITY_REQUEST_ORDERING:-canonical}"
    ;;
  L7)
    export PARITY_WORKER_COUNT="${PARITY_WORKER_COUNT:-2}"
    export PARITY_PARALLELISM_ENABLED="${PARITY_PARALLELISM_ENABLED:-true}"
    export PARITY_REQUEST_ORDERING="${PARITY_REQUEST_ORDERING:-canonical}"
    export PARITY_GENERATION_CACHE_POLICY="${PARITY_GENERATION_CACHE_POLICY:-canonical}"
    ;;
esac

cd "${REPO_ROOT}"
bash scripts/finetune/launch_local_candidate_gateway_dgx1_merged.sh
