#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEFAULT_TOKENIZER_PATH="${HOME}/.cache/huggingface/hub/models--Qwen--Qwen3-32B/snapshots/9216db5781bf21249d130ec9da846c4624c16137"

BIND_LEVEL="${BIND_LEVEL:-L0}"
BIND_LEVEL_SLUG="$(printf '%s' "${BIND_LEVEL}" | tr '[:upper:]' '[:lower:]')"

case "${BIND_LEVEL}" in
  L0) GATEWAY_PORT_DEFAULT=8010; LOCAL_TUNNEL_PORT_DEFAULT=30020 ;;
  L1) GATEWAY_PORT_DEFAULT=8011; LOCAL_TUNNEL_PORT_DEFAULT=30021 ;;
  L2) GATEWAY_PORT_DEFAULT=8012; LOCAL_TUNNEL_PORT_DEFAULT=30022 ;;
  L3) GATEWAY_PORT_DEFAULT=8013; LOCAL_TUNNEL_PORT_DEFAULT=30023 ;;
  L4) GATEWAY_PORT_DEFAULT=8014; LOCAL_TUNNEL_PORT_DEFAULT=30024 ;;
  L5) GATEWAY_PORT_DEFAULT=8015; LOCAL_TUNNEL_PORT_DEFAULT=30025 ;;
  L6) GATEWAY_PORT_DEFAULT=8016; LOCAL_TUNNEL_PORT_DEFAULT=30026 ;;
  *)
    echo "[FAIL] Unknown BIND_LEVEL=${BIND_LEVEL}" >&2
    exit 1
    ;;
esac

export RELEASE_LANE_ID="${RELEASE_LANE_ID:-rc_j_${BIND_LEVEL_SLUG}}"
export API_VERSION_LABEL="${API_VERSION_LABEL:-2026-03-24-${BIND_LEVEL_SLUG}}"
export GATEWAY_PORT="${GATEWAY_PORT:-${GATEWAY_PORT_DEFAULT}}"
export LOCAL_TUNNEL_PORT="${LOCAL_TUNNEL_PORT:-${LOCAL_TUNNEL_PORT_DEFAULT}}"
export LOG_NAME="${LOG_NAME:-bind_${BIND_LEVEL_SLUG}_gateway.log}"
export PID_NAME="${PID_NAME:-bind_${BIND_LEVEL_SLUG}_gateway.pid}"
export TUNNEL_LOG_NAME="${TUNNEL_LOG_NAME:-bind_${BIND_LEVEL_SLUG}_tunnel.log}"
export TUNNEL_PID_NAME="${TUNNEL_PID_NAME:-bind_${BIND_LEVEL_SLUG}_tunnel.pid}"
export AUDIT_LOG_PATH="${AUDIT_LOG_PATH:-${REPO_ROOT}/runtime_logs/bind_${BIND_LEVEL_SLUG}_audit.jsonl}"
export TRACE_LOG_DIR="${TRACE_LOG_DIR:-${REPO_ROOT}/runtime_logs/bind_${BIND_LEVEL_SLUG}_traces}"
export SESSION_STORE_NAMESPACE="${SESSION_STORE_NAMESPACE:-hukuk-ai-bind-${BIND_LEVEL_SLUG}}"
export PARITY_TRACE_ENABLED="${PARITY_TRACE_ENABLED:-true}"

export RELEASE_CONTROLS_STRICT=false
export API_AUTH_ENABLED=false
export AUDIT_LOG_ENABLED=false
export ALLOW_ANONYMOUS_INTERNAL_SMOKE=true
export SESSION_STORE_BACKEND=memory
export SESSION_STORE_REDIS_REQUIRED=false
export TOKEN_ACCOUNTING_APPROXIMATE_FALLBACK=true

case "${BIND_LEVEL}" in
  L1|L2|L3|L4|L5|L6)
    export AUDIT_LOG_ENABLED=true
    ;;
esac

case "${BIND_LEVEL}" in
  L2|L3|L4|L5|L6)
    export API_AUTH_ENABLED=true
    export ALLOW_ANONYMOUS_INTERNAL_SMOKE=false
    ;;
esac

case "${BIND_LEVEL}" in
  L3|L4|L5|L6)
    export SESSION_STORE_BACKEND=redis
    export SESSION_STORE_REDIS_REQUIRED=true
    export SESSION_STORE_REDIS_PING_ON_STARTUP=true
    export REDIS_URL="${REDIS_URL:-redis://127.0.0.1:6379/0}"
    ;;
esac

case "${BIND_LEVEL}" in
  L4|L5|L6)
    export TOKEN_ACCOUNTING_APPROXIMATE_FALLBACK=false
    export TOKEN_ACCOUNTING_TOKENIZER_PATH="${TOKEN_ACCOUNTING_TOKENIZER_PATH:-${DEFAULT_TOKENIZER_PATH}}"
    ;;
esac

cd "${REPO_ROOT}"
bash scripts/finetune/launch_local_candidate_gateway_dgx1_merged.sh
